server:
  port: 8082

spring:
  application:
    name: fraud

  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/fraud
    username: vicheanath
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true